spring.application.name=querie
server.port=8088

# Bootstrap server - usa kafka:29092 en Docker, localhost:9092 en local
spring.kafka.bootstrap-servers=localhost:9092

# --- Producer ---
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# --- Consumer ---
spring.kafka.consumer.group-id=productkafkaservice-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer 

# Tópicos a escuchar
kafka.topic.productos=productos-topico
kafka.topic.pagos=pagos-topico
kafka.topic.ordenes=ordenes-topico


# Datos de conexión
spring.datasource.url=jdbc:postgresql://localhost:5432/failed_products_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

# Estrategia de actualización de tablas
# 'update' es ideal para desarrollo porque crea la tabla de errores si no existe
spring.jpa.hibernate.ddl-auto=update

# Opcional: Para ver en consola qué está haciendo el Job de reintento
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# URL del microservicios para reintentos
payment.service.url=http://localhost:8082/pagos/procesar
order.service.url=http://localhost:8082/ordenes
product.service.url=http://localhost:8082/productos

# Configuración de Correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Le decimos a Java que confíe en el servidor de Gmail sin revisar su certificado a fondo
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# (Opcional pero recomendado) Forzamos una versión moderna de seguridad por si hay conflictos
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
